### ISSUE TITLE
Key error

### ISSUE THREAD

**Issue by RingoAl** [MamontenKa/YMS#1]
Добрый день.
Что-то не работает:
```
Traceback (most recent call last):
  File "downloader.py", line 194, in <module>
    yandex.download_and_safe_tracks()
  File "downloader.py", line 118, in download_and_safe_tracks
    track_ids = self.get_track_ids()
  File "downloader.py", line 77, in get_track_ids
    self.update_library(tracks, track_ids[:len(tracks)])
  File "downloader.py", line 84, in update_library
    if self.tracks_library.get(track_id_old) is None and track['type'] == 'music':
KeyError: 'type'
```

**Comment by rusachello** [comment]
Добрый день.
Проблема на аутентификации

```
Traceback (most recent call last):
  File "downloader.py", line 193, in <module>
    yandex.auth()
  File "downloader.py", line 61, in auth
    raise AuthError(f'Got error {auth_password["errors"]}')
__main__.AuthError: Got error ['captcha.required']
```

**Comment by MamontenKa** [comment]
> Добрый день.
> Проблема на аутентификации
> 
> ```
> Traceback (most recent call last):
>   File "downloader.py", line 193, in <module>
>     yandex.auth()
>   File "downloader.py", line 61, in auth
>     raise AuthError(f'Got error {auth_password["errors"]}')
> __main__.AuthError: Got error ['captcha.required']
> ```
Перенёс в отдельную issue но вряд ли решится, ибо идёт запрос каптчи, что никоем образом не решить :(





> Добрый день.
> Что-то не работает:
> 
> ```
> Traceback (most recent call last):
>   File "downloader.py", line 194, in <module>
>     yandex.download_and_safe_tracks()
>   File "downloader.py", line 118, in download_and_safe_tracks
>     track_ids = self.get_track_ids()
>   File "downloader.py", line 77, in get_track_ids
>     self.update_library(tracks, track_ids[:len(tracks)])
>   File "downloader.py", line 84, in update_library
>     if self.tracks_library.get(track_id_old) is None and track['type'] == 'music':
> KeyError: 'type'
> ```

Тут всё пофиксили.
